// Created by Crowbar 0.56

$modelname "vgui\UI_welcome01_screen.mdl"

$bodygroup "Body"
{
	studio "ui_welcome01_screen_UI_welcome01_reference.smd"
}

$include "ui_welcome01_screen_lod.qci"

$surfaceprop "default"

$contents "solid"

$illumposition 0.719 -208.579 57.56

$maxeyedeflection 90

$mostlyopaque

$cdmaterials "models\vgui\"

// $include "ui_welcome01_screen_box.qci"

$include "ui_welcome01_screen_bone.qci"

$include "ui_welcome01_screen_animation.qci"
